### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by mightyiam** [codingforpleasure/Distributed-javascript-project#1]

**Comment by codingforpleasure** [comment]
Hi Or,
The project's intention is to _maintain and to beautify literature_ via
collecting beautiful phrases taken from books which describe feelings and
emotions.
The site would hold a large database under the hood which are categorized
by emotion type. each main-node would hold a specific emotion, and all
surrounding neighbour nodes would be phrases which will be describing/ this
specific emotion.

The collection of phrases would be updated and evolved by the surfers who
can contribute easily to the site via there smart-phone app (OCR is
involved).

Nowadays I see Whats'up dialogue which consist only emojis, no special
words and no special meanings  :/ so I feel kind of sad.
It's usage is targeted to all age groups.

http://blog.appraptor.com/images/codeflower.png

There are few technical details I haven't mentioned yet,
but I hope I have explained my self quite well. Would you be interested? ;)

_Gil_

*-- Wear a smile - one size fits all ;-) *

**Comment by mightyiam** [comment]
Awesome. Keep it up.
